// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjLdrl4-hcrcXApOqu-I5wti4fcVHiLRg',
    appId: '1:722230081466:web:42982e7e3d52ac95ce4f83',
    messagingSenderId: '722230081466',
    projectId: 'pj-web-kop',
    authDomain: 'pj-web-kop.firebaseapp.com',
    storageBucket: 'pj-web-kop.appspot.com',
    measurementId: 'G-38WRMGRH20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvc-9EHAzl171uwft9NgxZFkbcjelWnEU',
    appId: '1:722230081466:android:cba9092d9967df90ce4f83',
    messagingSenderId: '722230081466',
    projectId: 'pj-web-kop',
    storageBucket: 'pj-web-kop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFs891ZT6xZkQb8DKUFuyZlJ9Is99jMyw',
    appId: '1:722230081466:ios:a3c1a859b66fc24fce4f83',
    messagingSenderId: '722230081466',
    projectId: 'pj-web-kop',
    storageBucket: 'pj-web-kop.appspot.com',
    iosBundleId: 'com.example.flutterUtilities2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFs891ZT6xZkQb8DKUFuyZlJ9Is99jMyw',
    appId: '1:722230081466:ios:a3c1a859b66fc24fce4f83',
    messagingSenderId: '722230081466',
    projectId: 'pj-web-kop',
    storageBucket: 'pj-web-kop.appspot.com',
    iosBundleId: 'com.example.flutterUtilities2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIPSqBKhm2nNRdJ-PPgv2KVOu4s7FnFPI',
    appId: '1:722230081466:web:22995ed22784ff68ce4f83',
    messagingSenderId: '722230081466',
    projectId: 'pj-web-kop',
    authDomain: 'pj-web-kop.firebaseapp.com',
    storageBucket: 'pj-web-kop.appspot.com',
    measurementId: 'G-ZQPHSWN5LK',
  );

}